services:
  node0:
    build:
      context: ./src
      dockerfile: Dockerfile
    command: ['0', '1', '5']
  node1:
    build:
      context: ./src
      dockerfile: Dockerfile
    command: ['1', '2', '4', '3', '0']
  node2:
    build:
      context: ./src
      dockerfile: Dockerfile
    command: ['2', '6', '1']
  node3:
    build:
      context: ./src
      dockerfile: Dockerfile
    command: ['3', '9', '1']
  node4:
    build:
      context: ./src
      dockerfile: Dockerfile
    command: ['4', '1']
  node5:
    build:
      context: ./src
      dockerfile: Dockerfile
    command: ['5', '7', '8', '0']
  node6:
    build:
      context: ./src
      dockerfile: Dockerfile
    command: ['6', '2']
  node7:
    build:
      context: ./src
      dockerfile: Dockerfile
    command: ['7', '5']
  node8:
    build:
      context: ./src
      dockerfile: Dockerfile
    command: ['8', '5']
  node9:
    build:
      context: ./src
      dockerfile: Dockerfile
    command: ['9', '3']
